---
drake_cache: ".ui"
dependencies: "dependencies"
output:
  html_tag:
    filename: "index.html"
    dirpath: "`r library(econR); .r %//% 'docs'`"
    object: "ui"
---


```{r makecondition}
library(dplyr)
library(shiny)
library(htmltools)
library(econR)
library(shinymaterial)
library(tibble)
```

```{r dependencies}
dependencies <- {
  myown_deps <- htmltools::htmlDependency(
      name="myown",
      version="1.0.0",
      src=c(file= .r %//%  "assets"),
      script = "js/myscript.js",
      stylesheet="css/mystyle.css"
    )
  econR_deps <- econR::html_dependencies()
  tagList(
    econR_deps$jquery(),
    econR_deps$materialise(),
    myown_deps
  )
}
```


## =======================

### Input

```{r input_bins}
sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
```

### Output

```{r output_leaflet}
output_leaflet <- leaflet::leafletOutput("leafletplot",width="100%", height="600px")
```

```{r output_choropleth}
output_choropleth <- plotly::plotlyOutput("plotlyplot",width="100%",height="600px")
```

```{r output_histplot}
output_histplot <- plotly::plotlyOutput("plothist",width="100%",height="600px")
```

```{r output_cumulative}
output_cumulative <- plotly::plotlyOutput("cumulative",width="100%",height="600px")
```

## =======================

### UI

```{r ui}
ui <- material_page(
  title = "Covid-19 Dashboard",
  nav_bar_fixed = F,
  nav_bar_color = "orange darken-3",
  font_color = "black",
  background_color="blue-grey lighten-4",
  # Place side-nav in the beginning of the UI
  material_side_nav(
    fixed = T,
    # Place side-nav tabs within side-nav
    material_side_nav_tabs(
      side_nav_tabs = c(
        "Location (Quarantined)" = "side_nav_tab_1",
        "Choropleth (Quarantined)" = "side_nav_tab_2",
        "Cumulative (Sorted by city)" = "side_nav_tab_4",
        "Timeseries" = "side_nav_tab_3"
      ),
      icons = c("map", "insert_chart","show_chart","location_city")
    )
  ),
  # Define side-nav tab content
  material_side_nav_tab_content(
    side_nav_tab_id = "side_nav_tab_1",
    tags$table(
      tags$thead(
        tags$tr(
          tags$th("地區"),
          tags$th("類別"),
          tags$th("數量")
        )
      ),
      tags$tbody(
        tags$tr(
          tags$td(tags$div(class="chip",tags$div(class="chip","新北市"))),
          tags$td(tags$div(class="chip",tags$div(class="chip","未解除隔離患者"))),
          tags$td("1935位 (僅包含地址填寫正確之數量)"
                  )
        )
      )
    ),
    output_leaflet
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "side_nav_tab_2",
    tags$table(
      tags$thead(
        tags$tr(
          tags$th("地區"),
          tags$th("類別"),
          tags$th("數量")
        )
      ),
      tags$tbody(
        tags$tr(
          tags$td(tags$div(class="chip",tags$div(class="chip","新北市"))),
          tags$td(tags$div(class="chip",tags$div(class="chip","未解除隔離患者"))),
          tags$td("1935位 (僅包含地址填寫正確之數量)")
        )
      )
    ),
    tags$div(class="container",
    output_choropleth)
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "side_nav_tab_3",
    tags$table(
      tags$thead(
        tags$tr(
          tags$th("地區"),
          tags$th("類別"),
          tags$th("數量")
        )
      ),
      tags$tbody(
        tags$tr(
          tags$td(tags$div(class="chip",tags$div(class="chip","新北市"))),
          tags$td(tags$div(class="chip",tags$div(class="chip","累積發病患者"))),
          tags$td("6315位")
        )
      )
    ),
    output_histplot
  ),
  material_side_nav_tab_content(
    side_nav_tab_id = "side_nav_tab_4",
    tags$table(
      tags$thead(
        tags$tr(
          tags$th("地區"),
          tags$th("類別"),
          tags$th("數量")
        )
      ),
      tags$tbody(
        tags$tr(
          tags$td(tags$div(class="chip",tags$div(class="chip","新北市"))),
          tags$td(tags$div(class="chip",tags$div(class="chip","累積發病患者"))),
          tags$td("6315位")
        )
      )
    ),
   output_cumulative
  )
)
```

## =======================


## Browse

```{r}
web$browse()
```





## JS


<!--JS end-->
