---
drake_cache: ".ui"
---

## Bootstrap Framework

   <https://getbootstrap.com/>
   
## Setup environment

  * Addins: Initiate drake -> `drake$source_plan()` -> `drake$makePlan()`.
  
  * `web$browse()` to see the output. 
  
  * If any change to Rmd, save the Rmd, then `drake$update()` -> `web$browser()` to see the change.
  
  * Your html output file is in `web$output_filepath()`.

```{r makecondition}
library(dplyr)
library(shiny)
library(htmltools)
library(econR)
.GlobalEnv$web <- econR::Web()
web$foldername="www" # output folder name
web$html_filename <- "index.html"

```

## =======================

### Input

```{r input_bins}
sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
```

### Output

```{r output_mapPlot}
output_mapPlot <- shiny::plotOutput("mapPlot")
```

## =======================

### UI

```{r ui}
ui <- tags$body(
  fluidPage(

    # Application title
    titlePanel("UI from ui.Rmd: Map Data trial"),

    # Sidebar with a slider input for number of bins 
    sidebarLayout(
        sidebarPanel(
            input_bins
        ),

        # Show a plot of the generated distribution
        mainPanel(
           output_mapPlot
        )
    )
))
```



## =======================

## Save

```{r save_ui}
.root <- rprojroot::is_rstudio_project$make_fix_file()
saveRDS(ui, file=file.path(.root(),"ui.RDS"))
```

## Browse

```{r}
web$browse()
```





## JS


<!--JS end-->
